### ISSUE TITLE
Install by conda

### ISSUE THREAD

**Issue by liaochenlanruo** [twylie/viromatch#1]
Have you ever tried to create a bioconda recipe so that users can use conda to install the software.

**Comment by twylie** [comment]
Thanks for your interest in ViroMatch and the feedback. We've consciously picked a single delivery method (i.e. Docker) to officially support, based on our collaborators and the adoption of containers across cloud-based platforms. The Docker image also includes non-Python prerequisites required to run the pipeline. If you wish to manually install the components locally, a good place to start is looking at the Dockerfile:

https://github.com/twylie/viromatch/blob/main/Dockerfile

...which walks through the installation logic step-by-step.
