### ISSUE TITLE
Running single-end read files?

### ISSUE THREAD

**Issue by kwnamhang** [twylie/viromatch#4]
Hi Tyler, does viromatch support single end read files? I wondered whether there was an easy workaround when you only have a single input fastq. Many thanks in advance.

**Comment by twylie** [comment]
ViroMatch doesn't officially accept single-end data; however, it also doesn't explicitly use paired-end alignments. We require paired-end FASTQ files for housekeeping purposes in ViroMatch, as this is the standard format in which our sequencing files come.

You should be able to hack your input FASTQ files to run in ViroMatch by simply splitting your single-end FASTQ in half and feeding it to ViroMatch. Example:

--input part1.fastq part2.fastq

This is a hack... so keep in mind the R1/R2 designations in the ViroMatch report files will not be reflective of paired-end-ness, but rather the arbitrary splitting of your original single-end FASTQ file.

**Comment by kwnamhang** [comment]
Great, many thanks Tyler. Noted that this is a hack and will keep in mind during interpretation of the report files. Much appreciated!
